config/routes.rb
Rails.application.routes.draw do
  resources :permissions
  resources :user_roles
  get 'user_roles/index'

  resources :roles
  resources :user_groups
  post '/rate' => 'rater#create', :as => 'rate'
  get '/not_found' => 'homes#not_found'
  get '/test_mobile' => 'homes#test_mobile'
  get '/test_ajax' => 'homes#test_ajax'
  get '/autosearch' => 'homes#autosearch'
  get 'finalexam' => 'homes#final_exam'
  resources :reviews, except: [:show, :index]
  devise_for :users
  root 'homes#index'
  resources :movies do
    collection do
      get 'search'
    end
    resources :reviews, except: [:show, :index]
  end
   resource :user_roles
  # get '/user_roles' => "user_roles#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
      p= Hash.new
      user.roles.each do |role|
        p["#{role.name}"] = role.ctrl
      end
      ug = user.user_group
      ug.roles.each do |role|
        p["#{role.name}"] = role.ctrl
      end
      p.map do |key, value|
        can :"#{key}", "#{value}".constantize
      end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

app/models/movie.rb
class Movie < ApplicationRecord
  belongs_to :user
  has_many :reviews
  has_attached_file :image, styles: { thumb: "100x100>", square: "300x300>", rectangle: "700*400>" }, default_url: "/images/:style/nophoto.png"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
  ratyrate_rateable 'visual_effects', 'original_score', 'director', 'custome_design'
  self.per_page = 3
  def self.search(search)
    search ? where("title LIKE ?", "%#{search[:title]}%") : all
  end
end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

app/models/permission.rb
class Permission < ApplicationRecord
  belongs_to :user_group
  belongs_to :role
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :movie
end

app/models/role.rb
class Role < ApplicationRecord
  has_many :user_roles
  has_many :users , through: :user_roles
  has_many :permissions
  has_many :user_groups, through: :permissions
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :movies
  belongs_to :user_group
  has_many :reviews, dependent: :destroy
  has_many :user_roles
  has_many :roles, through: :user_roles

  before_create :set_default_group
  private
  def set_default_group
    self.user_group ||= UserGroup.find(2)
  end
end

app/models/user_group.rb
class UserGroup < ApplicationRecord
  has_many :users
  has_many :permissions
  has_many :roles, through: :permissions
end

app/models/user_role.rb
class UserRole < ApplicationRecord
  belongs_to :user
  belongs_to :role
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
    add_breadcrumb "Home", :root_path
    @movies = Movie.search(params[:search]).paginate(:page => params[:page])
  end

  def show
    add_breadcrumb "Show", :movies_path
  end

  def not_found

  end

  def test_mobile
    @roles = Role.all
    @role = Role.new
  end

  def test_ajax
    movies = Movie.where("title like ?", "%#{params[:term]}%")
    if movies.count == 0
      render json: {"no_result": "no result"}
    end
    render json: movies.map(&:title)
  end

  def autosearch
    movies = Movie.all
    render json: movies
  end

  def final_exam

  end
end

app/controllers/permissions_controller.rb
class PermissionsController < ApplicationController
  before_action :set_permission, only: [:show, :edit, :update, :destroy]

  # GET /permissions
  # GET /permissions.json
  def index
    @permissions = Permission.all.order("user_group_id")
  end

  # GET /permissions/1
  # GET /permissions/1.json
  def show
  end

  # GET /permissions/new
  def new
    @permission = Permission.new
  end

  # GET /permissions/1/edit
  def edit
  end

  # POST /permissions
  # POST /permissions.json
  def create
    @permission = Permission.new(permission_params)

    respond_to do |format|
      if @permission.save
        format.html { redirect_to @permission, notice: 'Permission was successfully created.' }
        format.json { render :show, status: :created, location: @permission }
      else
        format.html { render :new }
        format.json { render json: @permission.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /permissions/1
  # PATCH/PUT /permissions/1.json
  def update
    respond_to do |format|
      if @permission.update(permission_params)
        format.html { redirect_to @permission, notice: 'Permission was successfully updated.' }
        format.json { render :show, status: :ok, location: @permission }
      else
        format.html { render :edit }
        format.json { render json: @permission.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /permissions/1
  # DELETE /permissions/1.json
  def destroy
    @permission.destroy
    respond_to do |format|
      format.html { redirect_to permissions_url, notice: 'Permission was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_permission
      @permission = Permission.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def permission_params
      params.require(:permission).permit(:user_group_id, :role_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def sortable(column, title = nil)
    title ||= column.titleize
    direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
    link_to title, {:sort => column, :direction => direction}
  end
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
  def youtube_embed(youtube_url)
    if youtube_url[/youtu\.be\/([^\?]*)/]
      youtube_id = $1
    else
      # Regex from # http://stackoverflow.com/questions/3452546/javascript-regex-how-to-get-youtube-video-id-from-url/4811367#4811367
      youtube_url[/^.*((v\/)|(embed\/)|(watch\?))\??v?=?([^\&\?]*).*/]
      youtube_id = $5
    end

    %Q{<iframe title="YouTube video player" width="640" height="390" src="http://www.youtube.com/embed/#{ youtube_id }" frameborder="0" allowfullscreen></iframe>}
  end
end

app/helpers/permissions_helper.rb
module PermissionsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/user_groups_helper.rb
module UserGroupsHelper
end

app/helpers/user_roles_helper.rb
module UserRolesHelper
end

app/views/permissions/_form.html.erb
<%= simple_form_for(@permission) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.association :user_group %>
    <%= f.association :role,:label_method => lambda { |role| "#{role.name}  #{role.ctrl}"}, required: true %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/permissions/edit.html.erb
<h1>Editing Permission</h1>

<%= render 'form', permission: @permission %>

<%= link_to 'Show', @permission %> |
<%= link_to 'Back', permissions_path %>

app/views/permissions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Permissions</h1>
<%= link_to (raw("<button type=\"button\" class=\"btn btn-default\"><span class=\"glyphicon glyphicon-plus\"></span> " + "New" + "</button>")), new_permission_path %>
<p></p>
<table class="table table-bordered table-striped fill">
  <thead>
    <tr>
      <th>User group</th>
      <th>Role</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @permissions.each do |permission| %>
      <tr>
        <td><%= permission.user_group.name %></td>
        <td><%= permission.role.name + " " + permission.role.ctrl %></td>
        <td><%= link_to 'Edit', edit_permission_path(permission) %></td>
        <td><%= link_to 'Destroy', permission, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/permissions/new.html.erb
<h1>New Permission</h1>

<%= render 'form', permission: @permission %>

<%= link_to 'Back', permissions_path %>

app/views/permissions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User group:</strong>
  <%= @permission.user_group.name %>
</p>

<p>
  <strong>Role:</strong>
  <%= @permission.role.name + " " + @permission.role.ctrl %>
</p>

<%= link_to 'Edit', edit_permission_path(@permission) %> |
<%= link_to 'Back', permissions_path %>