config/routes.rb
Rails.application.routes.draw do
  resources :permissions
  resources :user_roles
  get 'user_roles/index'

  resources :roles
  resources :user_groups
  post '/rate' => 'rater#create', :as => 'rate'
  get '/not_found' => 'homes#not_found'
  get '/test_mobile' => 'homes#test_mobile'
  get '/test_ajax' => 'homes#test_ajax'
  get '/autosearch' => 'homes#autosearch'
  get 'finalexam' => 'homes#final_exam'
  resources :reviews, except: [:show, :index]
  devise_for :users
  root 'homes#index'
  resources :movies do
    collection do
      get 'search'
    end
    resources :reviews, except: [:show, :index]
  end
   resource :user_roles
  # get '/user_roles' => "user_roles#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
      p= Hash.new
      user.roles.each do |role|
        p["#{role.name}"] = role.ctrl
      end
      ug = user.user_group
      ug.roles.each do |role|
        p["#{role.name}"] = role.ctrl
      end
      p.map do |key, value|
        can :"#{key}", "#{value}".constantize
      end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

app/models/movie.rb
class Movie < ApplicationRecord
  belongs_to :user
  has_many :reviews
  has_attached_file :image, styles: { thumb: "100x100>", square: "300x300>", rectangle: "700*400>" }, default_url: "/images/:style/nophoto.png"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
  ratyrate_rateable 'visual_effects', 'original_score', 'director', 'custome_design'
  self.per_page = 3
  def self.search(search)
    search ? where("title LIKE ?", "%#{search[:title]}%") : all
  end
end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

app/models/permission.rb
class Permission < ApplicationRecord
  belongs_to :user_group
  belongs_to :role
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :movie
end

app/models/role.rb
class Role < ApplicationRecord
  has_many :user_roles
  has_many :users , through: :user_roles
  has_many :permissions
  has_many :user_groups, through: :permissions
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :movies
  belongs_to :user_group
  has_many :reviews, dependent: :destroy
  has_many :user_roles
  has_many :roles, through: :user_roles

  before_create :set_default_group
  private
  def set_default_group
    self.user_group ||= UserGroup.find(2)
  end
end

app/models/user_group.rb
class UserGroup < ApplicationRecord
  has_many :users
  has_many :permissions
  has_many :roles, through: :permissions
end

app/models/user_role.rb
class UserRole < ApplicationRecord
  belongs_to :user
  belongs_to :role
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
    add_breadcrumb "Home", :root_path
    @movies = Movie.search(params[:search]).paginate(:page => params[:page])
  end

  def show
    add_breadcrumb "Show", :movies_path
  end

  def not_found

  end

  def test_mobile
    @roles = Role.all
    @role = Role.new
  end

  def test_ajax
    movies = Movie.where("title like ?", "%#{params[:term]}%")
    if movies.count == 0
      render json: {"no_result": "no result"}
    end
    render json: movies.map(&:title)
  end

  def autosearch
    movies = Movie.all
    render json: movies
  end

  def final_exam

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def sortable(column, title = nil)
    title ||= column.titleize
    direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
    link_to title, {:sort => column, :direction => direction}
  end
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
  def youtube_embed(youtube_url)
    if youtube_url[/youtu\.be\/([^\?]*)/]
      youtube_id = $1
    else
      # Regex from # http://stackoverflow.com/questions/3452546/javascript-regex-how-to-get-youtube-video-id-from-url/4811367#4811367
      youtube_url[/^.*((v\/)|(embed\/)|(watch\?))\??v?=?([^\&\?]*).*/]
      youtube_id = $5
    end

    %Q{<iframe title="YouTube video player" width="640" height="390" src="http://www.youtube.com/embed/#{ youtube_id }" frameborder="0" allowfullscreen></iframe>}
  end
end

app/helpers/permissions_helper.rb
module PermissionsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/user_groups_helper.rb
module UserGroupsHelper
end

app/helpers/user_roles_helper.rb
module UserRolesHelper
end

app/views/homes/_role.html.erb
<table class="table table-bordered table-striped fill">
  <thead>
  <tr>
    <th>Role</th>
    <th>Controller</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @roles.each do |role| %>
      <tr id="role_<%= role.id %>">
        <td><%= role.name %></td>
        <td><%= role.ctrl %></td>
        <td><%= link_to 'Show', role %></td>
        <td><%= link_to 'Edit', edit_role_path(role) %></td>
        <td><%= link_to 'Destroy', role, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/homes/_search.html.erb
<div class="row fill">
  <div class="col-lg-4">
    <%= simple_form_for :search,:remote => true, url: movies_path, :method => :get do |f| %>
        <div class="input-group">
          <%= f.text_field :title, id:'search',placeholder: 'Search', class: 'form-control' %>
        </div>
        <input type="submit" value="Submit">
    <% end %>
  </div>
</div>

app/views/homes/index.html.erb
<div class="row">
  <div id="the-basics" class="col-sm-4">
    <%= simple_form_for :search,:remote => true, url: root_path,:html =>{id: 'movie_search'}, :method => :get do |f| %>
        <div class="input-group">
        <%= f.text_field :title, placeholder: 'Search',autocomplete:"off", class: 'form-control typeahead',id:'search',:value => (params[:search].nil?)?'':params[:search][:title] %>
          <span class="input-group-btn">
              <%= f.button :submit, 'Search', class: 'btn btn-default' %>
            </span>
        </div>
    <% end %>
  </div>
</div>
<br>
<% @movies.each_slice(3) do |movies| %>
    <div class="row">
      <% movies.each do |movie| %>
          <div class="col-md-4 portfolio-item">
            <div class="thumbnail">
              <%= link_to (image_tag movie.image.url(:rectangle)), movie, class: "img-responsive" %>

              <h3>
                <%= link_to movie.title, movie %></td>
              </h3>
              <p><%= movie.description[0..122] %></p>
            </div>
          </div>
      <% end %>
    </div>
<% end %>
<%= will_paginate @movies, :previous_label => t(:previous), :next_label => t(:next), class: 'pull-right' %>

<div id="results">
</div>
<style>
  ul.ui-autocomplete {
    position: absolute;
    list-style: none;
    margin: 0;
    padding: 0;
    border: solid 1px #999;
    cursor: default;
  }
  ul.ui-autocomplete li {
    background-color: #FFF;
    border-top: solid 1px #DDD;
    margin: 0;
    padding: 0;
  }
  ul.ui-autocomplete a {
    color: #000;
    display: block;
    padding: 3px;
  }
  ul.ui-autocomplete a.ui-state-hover,ul.ui-autocomplete  a.ui-state-active {
    background-color: #FFFCB2;
  }
  .ui-helper-hidden-accessible { display:none; }

</style>

<script>
  $(document).ready(function () {
    $('#search').change(function () {
        $('#movie_search').submit();
    });
  })
</script>

app/views/homes/index.js.erb
alert('ok')

app/views/homes/show.html.erb
<%= render 'search' %>
<p>
  <strong>Title:</strong>
  <%= @movie.title %>
</p>
<p>
  <%= image_tag @movie.image.url(:square) %>
</p>
<p>
  <strong>Description:</strong>
  <%= @movie.description %>
</p>

<p>
  <strong>Length:</strong>
  <%= @movie.length %>
</p>

<p>
  <strong>Release year:</strong>
  <%= @movie.release_year %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @movie.rating %>
</p>

app/views/homes/test_mobile.html.erb
<a href="#" onclick="this.style.color='#009900';">Paint it green</a>