config/routes.rb
Rails.application.routes.draw do
  resources :permissions
  resources :user_roles
  get 'user_roles/index'

  resources :roles
  resources :user_groups
  post '/rate' => 'rater#create', :as => 'rate'
  get '/not_found' => 'homes#not_found'
  get '/test_mobile' => 'homes#test_mobile'
  get '/test_ajax' => 'homes#test_ajax'
  get '/autosearch' => 'homes#autosearch'
  get 'finalexam' => 'homes#final_exam'
  resources :reviews, except: [:show, :index]
  devise_for :users
  root 'homes#index'
  resources :movies do
    collection do
      get 'search'
    end
    resources :reviews, except: [:show, :index]
  end
   resource :user_roles
  # get '/user_roles' => "user_roles#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
      p= Hash.new
      user.roles.each do |role|
        p["#{role.name}"] = role.ctrl
      end
      ug = user.user_group
      ug.roles.each do |role|
        p["#{role.name}"] = role.ctrl
      end
      p.map do |key, value|
        can :"#{key}", "#{value}".constantize
      end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

app/models/movie.rb
class Movie < ApplicationRecord
  belongs_to :user
  has_many :reviews
  has_attached_file :image, styles: { thumb: "100x100>", square: "300x300>", rectangle: "700*400>" }, default_url: "/images/:style/nophoto.png"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
  ratyrate_rateable 'visual_effects', 'original_score', 'director', 'custome_design'
  self.per_page = 3
  def self.search(search)
    search ? where("title LIKE ?", "%#{search[:title]}%") : all
  end
end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

app/models/permission.rb
class Permission < ApplicationRecord
  belongs_to :user_group
  belongs_to :role
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :movie
end

app/models/role.rb
class Role < ApplicationRecord
  has_many :user_roles
  has_many :users , through: :user_roles
  has_many :permissions
  has_many :user_groups, through: :permissions
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :movies
  belongs_to :user_group
  has_many :reviews, dependent: :destroy
  has_many :user_roles
  has_many :roles, through: :user_roles

  before_create :set_default_group
  private
  def set_default_group
    self.user_group ||= UserGroup.find(2)
  end
end

app/models/user_group.rb
class UserGroup < ApplicationRecord
  has_many :users
  has_many :permissions
  has_many :roles, through: :permissions
end

app/models/user_role.rb
class UserRole < ApplicationRecord
  belongs_to :user
  belongs_to :role
end

app/helpers/application_helper.rb
module ApplicationHelper
  def sortable(column, title = nil)
    title ||= column.titleize
    direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
    link_to title, {:sort => column, :direction => direction}
  end
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
  def youtube_embed(youtube_url)
    if youtube_url[/youtu\.be\/([^\?]*)/]
      youtube_id = $1
    else
      # Regex from # http://stackoverflow.com/questions/3452546/javascript-regex-how-to-get-youtube-video-id-from-url/4811367#4811367
      youtube_url[/^.*((v\/)|(embed\/)|(watch\?))\??v?=?([^\&\?]*).*/]
      youtube_id = $5
    end

    %Q{<iframe title="YouTube video player" width="640" height="390" src="http://www.youtube.com/embed/#{ youtube_id }" frameborder="0" allowfullscreen></iframe>}
  end
end

app/helpers/permissions_helper.rb
module PermissionsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/user_roles_helper.rb
module UserRolesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MovieReview</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">Movie Review</a>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav pull-right">
            <% if user_signed_in? %>
                <% if current_user.user_group.name =="admin" %>
                    <li> <%= link_to "Manage Movie",movies_path %> </li>
                    <li> <%= link_to "Manage Role",roles_path %> </li>
                    <li> <%= link_to "Manage Permission",permissions_path %> </li>
                <% end %>
                <li> <%= link_to current_user.email,"#" %></li>
                <li><%= link_to "Logout", destroy_user_session_path, :method => 'delete' %></li>
                </ul>
            <% else %>
                <li><%= link_to "Log in", new_user_session_path %></li>
                <li><%= link_to "Sign up", new_user_registration_path%></li>
            <% end %>
          </ul>
        </div>
        <!-- /.navbar-collapse -->
      </div>
      <!-- /.container -->
    </nav>

  <div class="container">

    <% if notice != nil %>
        <div class="alert alert-success alert-dismissible" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Đóng"><span aria-hidden="true">&times;</span></button>
          <strong>Notice: </strong> <%= notice %>
        </div>
    <% end %>

    <% if alert != nil %>
        <div class="alert alert-danger alert-dismissible" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Đóng"><span aria-hidden="true">&times;</span></button>
          <strong>Alert: </strong> <%= alert %>
        </div>
    <% end %>
    <div class="row">
      <div class="col-lg-12">
      </div>
    </div>
    <%= yield %>
  </div>
  </body>
</html>